[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"
  NODE_VERSION = "20"


[build]
  command = "yarn build"
  publish = "dist"

[[plugins]]
  package = "netlify-plugin-cypress"

[context.deploy-preview]
  command = "yarn build:preview"

[dev]
  framework = "hugo"
  targetPort = 3000

  [plugins.inputs]
    record = true