baseURL = "https://www.lacritica.ar/"
languageCode = "en-us"
title = "La Crítica del Derecho"
theme = "hugo-xmag"

# Enable syntax highlighting, RSS, etc.
paginate = 10
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  
[params]
  description = "La Crítica del Derecho"
  footer = "&copy; 2025 La Crítica del Derecho Colectivo Crítico"

# Optional: social links
[[params.social]]
  name = "GitHub"
  url = "https://github.com/lacritica"

[[params.social]]
  name = "Twitter"
  url = "https://twitter.com/lacritica"

# Optional: main menu items
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Eventos"
  url = "/events/"
  weight = 3

[[menu.main]]
  name = "Nosotros"
  url = "/nosotros/"
  weight = 2

[permalinks]
  authors = "/authors/:slug/"

[slug]
remove_accents = true

[outputs]
home = ["HTML", "JSON"]

